const chalk = require('chalk');

/**
 * Extending chalk with custom colors. Having them in golgoth allow easier
 * re-use of them accross projects
 **/
module.exports = {
  ...chalk,
  bgBlackBright: chalk.bgBlackBright,
  bgBlack: chalk.bgBlack,
  bgBlueBright: chalk.bgBlueBright,
  bgBlue: chalk.bgBlue,
  bgCyanBright: chalk.bgCyanBright,
  bgCyan: chalk.bgCyan,
  bgGreenBright: chalk.bgGreenBright,
  bgGreen: chalk.bgGreen,
  bgMagentaBright: chalk.bgMagentaBright,
  bgMagenta: chalk.bgMagenta,
  bgRedBright: chalk.bgRedBright,
  bgRed: chalk.bgRed,
  bgWhiteBright: chalk.bgWhiteBright,
  bgWhite: chalk.bgWhite,
  bgYellowBright: chalk.bgYellowBright,
  bgYellow: chalk.bgYellow,
  black: chalk.ansi256('233'),
  blueBright: chalk.blueBright,
  blue: chalk.ansi256('69'),
  bold: chalk.bold,
  calmBlue: chalk.ansi256('67'),
  calmGreen: chalk.ansi256('108'),
  calmOrange: chalk.ansi256('209'),
  calmPurple: chalk.ansi256('141'),
  calmRed: chalk.ansi256('203'),
  calmYellow: chalk.ansi256('185'),
  cyanBright: chalk.cyanBright,
  cyan: chalk.cyan,
  darkBlue: chalk.ansi256('24'),
  darkGray: chalk.ansi256('235'),
  darkGreen: chalk.ansi256('28'),
  darkGrey: chalk.ansi256('235'),
  darkOrange: chalk.ansi256('166'),
  darkPurple: chalk.ansi256('55'),
  darkYellow: chalk.ansi256('136'),
  darkred: chalk.ansi256('88'),
  dim: chalk.dim,
  gray: chalk.ansi256('241'),
  greenBright: chalk.greenBright,
  green: chalk.ansi256('35'),
  grey: chalk.ansi256('241'),
  hidden: chalk.hidden,
  inverse: chalk.inverse,
  italic: chalk.italic,
  lightGray: chalk.ansi256('250'),
  lightGrey: chalk.ansi256('250'),
  magentaBright: chalk.magentaBright,
  magenta: chalk.magenta,
  orange: chalk.ansi256('202'),
  pureBlack: chalk.ansi256('16'),
  pureWhite: chalk.ansi256('255'),
  purple: chalk.ansi256('171'),
  redBright: chalk.redBright,
  red: chalk.ansi256('160'),
  reset: chalk.reset,
  strikethrough: chalk.strikethrough,
  underline: chalk.underline,
  visible: chalk.visible,
  whiteBright: chalk.whiteBright,
  white: chalk.ansi256('252'),
  yellowBright: chalk.yellowBright,
  yellow: chalk.ansi256('184'),
};
